// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_bYLWri2VLIftvkz4J4ySElNiufqhV8M',
    appId: '1:221653425486:web:566f0687dfaae89406921f',
    messagingSenderId: '221653425486',
    projectId: 'techhunt-978b1',
    authDomain: 'techhunt-978b1.firebaseapp.com',
    storageBucket: 'techhunt-978b1.appspot.com',
    measurementId: 'G-HGBTXNRVNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgGjuBPNxJ7v8qGL0mn_rywiognWODDE',
    appId: '1:221653425486:android:10e14f02b456a3d006921f',
    messagingSenderId: '221653425486',
    projectId: 'techhunt-978b1',
    storageBucket: 'techhunt-978b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1x9c5i_9FIGT2Ybw8_3uB3OYd8JfSm0',
    appId: '1:221653425486:ios:02b47a405059861506921f',
    messagingSenderId: '221653425486',
    projectId: 'techhunt-978b1',
    storageBucket: 'techhunt-978b1.appspot.com',
    iosBundleId: 'com.example.techHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1x9c5i_9FIGT2Ybw8_3uB3OYd8JfSm0',
    appId: '1:221653425486:ios:02b47a405059861506921f',
    messagingSenderId: '221653425486',
    projectId: 'techhunt-978b1',
    storageBucket: 'techhunt-978b1.appspot.com',
    iosBundleId: 'com.example.techHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_bYLWri2VLIftvkz4J4ySElNiufqhV8M',
    appId: '1:221653425486:web:75c327b0610f1ca206921f',
    messagingSenderId: '221653425486',
    projectId: 'techhunt-978b1',
    authDomain: 'techhunt-978b1.firebaseapp.com',
    storageBucket: 'techhunt-978b1.appspot.com',
    measurementId: 'G-GR1W036CC1',
  );
}
